services:
  postgres:
    image: postgres
    container_name: becayisbul_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    container_name: becayis_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./dorms.json:/app/dorms.json
      - ./.env:/app/.env
    working_dir: /app

volumes:
  pgdata:
