spring:
  application:
    name: kykbecayis
  datasource:
    url: jdbc:postgresql://localhost:5432/becayis_db
    username: becayis
    password: eecm7777
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    path: /api/
  api-docs:
    path: /api/v3/api-docs
  show-actuator: false
  default-produces-media-type: application/json
server:
  forward-headers-strategy: framework
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
  level:
    root: INFO
